apiVersion: v1
kind: Service
metadata:
  name: coinbase-service
spec:
  type: NodePort
  selector:
    app: coinbase-service-green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
